In [1]:
%matplotlib notebook

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np

In [3]:
# Read songs.csv file
artist_data = pd.read_csv("artist_data.csv")

In [61]:
artist_data

,Position,Artist,Genre,Lead Streams,Featured streams,Tracks,1b,100m,10m,1m,Update,% Songs Streamed 1Million Times,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058","17,624,649,510",248,6,117,241.0,244,11.04.22,98%,97%,47%,2%
1,2,Ed Sheeran,Pop,"35,009,165,977","2,537,534,050",222,10,59,166.0,200,11.04.22,90%,75%,27%,5%
2,3,Bad Bunny,Latin Trap,"33,838,992,346","4,440,723,306",141,3,89,134.0,140,11.04.22,99%,95%,63%,2%
3,4,The Weeknd,R&B/Soul,"30,759,273,612","3,858,847,246",178,6,69,143.0,161,11.04.22,90%,80%,39%,3%
4,5,Ariana Grande,Pop,"30,199,885,343","1,934,573,510",181,5,69,126.0,175,11.04.22,97%,70%,38%,3%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Upchurch,NaN,"1,233,720,207","136,998,161",225,0,0,29.0,177,03.03.22,79%,13%,0%,0%
996,997,Hungria Hip Hop,NaN,"1,233,176,813","69,096,039",63,0,1,37.0,59,04.12.21,94%,59%,2%,0%
997,998,Chicago,NaN,"1,232,497,152",5,725,0,4,11.0,56,22.03.22,8%,2%,1%,0%
998,999,Riton,NaN,"1,231,385,490","21,351,886",118,0,3,8.0,24,01.03.22,20%,7%,3%,0%
999,1000,BIGBANG,NaN,"1,231,303,296",1,381,0,2,23.0,60,09.04.22,16%,6%,1%,0%

In [5]:
# print colummns list 
print(artist_data.columns)

Index(['Position', 'Artist', 'Genre', 'Lead Streams', 'Featured streams',
       'Tracks', '1b', '100m', '10m', '1m', 'Update',
       '% Songs Streamed 1Million Times', '% Songs Streamed 10Million Times',
       '% Songs Streamed 100Million Times', '% Songs Streamed 1Billion Times'],
      dtype='object')

In [6]:
# convert to dataframe
artist_df = pd.DataFrame(artist_data)

In [7]:
# Show df
artist_df

,Position,Artist,Genre,Lead Streams,Featured streams,Tracks,1b,100m,10m,1m,Update,% Songs Streamed 1Million Times,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058","17,624,649,510",248.0,6,117,241.0,244,11.04.22,98%,97%,47%,2%
1,2,Ed Sheeran,Pop,"35,009,165,977","2,537,534,050",222.0,10,59,166.0,200,11.04.22,90%,75%,27%,5%
2,3,Bad Bunny,Latin Trap,"33,838,992,346","4,440,723,306",141.0,3,89,134.0,140,11.04.22,99%,95%,63%,2%
3,4,The Weeknd,R&B/Soul,"30,759,273,612","3,858,847,246",178.0,6,69,143.0,161,11.04.22,90%,80%,39%,3%
4,5,Ariana Grande,Pop,"30,199,885,343","1,934,573,510",181.0,5,69,126.0,175,11.04.22,97%,70%,38%,3%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Upchurch,NaN,"1,233,720,207","136,998,161",225.0,0,0,29.0,177,03.03.22,79%,13%,0%,0%
996,997,Hungria Hip Hop,NaN,"1,233,176,813","69,096,039",63.0,0,1,37.0,59,04.12.21,94%,59%,2%,0%
997,998,Chicago,NaN,"1,232,497,152",5,725.0,0,4,11.0,56,22.03.22,8%,2%,1%,0%
998,999,Riton,NaN,"1,231,385,490","21,351,886",118.0,0,3,8.0,24,01.03.22,20%,7%,3%,0%
999,1000,BIGBANG,NaN,"1,231,303,296",1,381.0,0,2,23.0,60,09.04.22,16%,6%,1%,0%

In [8]:
artist_df.describe()

,Position,Tracks,1b,100m,10m,1m
count,1000.000000,1000.000000,1000.000000,1000.000000,998.000000,1000.000000
mean,500.500000,185.574921,0.289000,8.133000,44.651303,115.270000
std,288.819436,164.501797,0.917781,10.380417,30.847258,72.643087
min,1.000000,1.028000,0.000000,0.000000,0.000000,10.000000
25%,250.750000,81.000000,0.000000,3.000000,24.000000,66.750000
50%,500.500000,138.000000,0.000000,5.000000,36.500000,97.000000
75%,750.250000,233.000000,0.000000,9.000000,56.000000,145.000000
max,1000.000000,979.000000,10.000000,117.000000,246.000000,606.000000

In [9]:
# Mean No. of tracks = 186, 
# SD = 164.50, 
# Max No.of tracks = 979,
# Min No. of tracks = 1.03    *** need to clean data as cannot have floats****
# Median 1st quartile = 81,
# Median 2nd quartile = 138,
# Median 3rd quartile = 233

## Data cleanup remove rows with errors - Tracks as floats convert to integers

In [10]:
s = artist_df['Tracks']
artist_df['Tracks'] = artist_df['Tracks'].astype(int)

artist_df = artist_df[artist_df['Tracks'] == s]
print(artist_df)

     Position           Artist       Genre    Lead Streams Featured streams  \
0           1            Drake     Hip-Hop  45,930,207,058   17,624,649,510
1           2       Ed Sheeran         Pop  35,009,165,977    2,537,534,050
2           3        Bad Bunny  Latin Trap  33,838,992,346    4,440,723,306
3           4       The Weeknd    R&B/Soul  30,759,273,612    3,858,847,246
4           5    Ariana Grande         Pop  30,199,885,343    1,934,573,510
..        ...              ...         ...             ...              ...
995       996         Upchurch         NaN   1,233,720,207      136,998,161
996       997  Hungria Hip Hop         NaN   1,233,176,813       69,096,039
997       998          Chicago         NaN   1,232,497,152                5
998       999            Riton         NaN   1,231,385,490       21,351,886
999      1000          BIGBANG         NaN   1,231,303,296                1

     Tracks  1b  100m    10m   1m    Update % Songs Streamed 1Million Times  \
0       248   6   117  241.0  244  11.04.22                             98%
1       222  10    59  166.0  200  11.04.22                             90%
2       141   3    89  134.0  140  11.04.22                             99%
3       178   6    69  143.0  161  11.04.22                             90%
4       181   5    69  126.0  175  11.04.22                             97%
..      ...  ..   ...    ...  ...       ...                             ...
995     225   0     0   29.0  177  03.03.22                             79%
996      63   0     1   37.0   59  04.12.21                             94%
997     725   0     4   11.0   56  22.03.22                              8%
998     118   0     3    8.0   24  01.03.22                             20%
999     381   0     2   23.0   60  09.04.22                             16%

    % Songs Streamed 10Million Times % Songs Streamed 100Million Times  \
0                                97%                               47%
1                                75%                               27%
2                                95%                               63%
3                                80%                               39%
4                                70%                               38%
..                               ...                               ...
995                              13%                                0%
996                              59%                                2%
997                               2%                                1%
998                               7%                                3%
999                               6%                                1%

    % Songs Streamed 1Billion Times
0                                2%
1                                5%
2                                2%
3                                3%
4                                3%
..                              ...
995                              0%
996                              0%
997                              0%
998                              0%
999                              0%

[972 rows x 15 columns]

In [11]:
artist_df.head()

,Position,Artist,Genre,Lead Streams,Featured streams,Tracks,1b,100m,10m,1m,Update,% Songs Streamed 1Million Times,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058","17,624,649,510",248,6,117,241.0,244,11.04.22,98%,97%,47%,2%
1,2,Ed Sheeran,Pop,"35,009,165,977","2,537,534,050",222,10,59,166.0,200,11.04.22,90%,75%,27%,5%
2,3,Bad Bunny,Latin Trap,"33,838,992,346","4,440,723,306",141,3,89,134.0,140,11.04.22,99%,95%,63%,2%
3,4,The Weeknd,R&B/Soul,"30,759,273,612","3,858,847,246",178,6,69,143.0,161,11.04.22,90%,80%,39%,3%
4,5,Ariana Grande,Pop,"30,199,885,343","1,934,573,510",181,5,69,126.0,175,11.04.22,97%,70%,38%,3%

In [12]:
artist_df.describe()

          Position      Tracks          1b        100m         10m          1m
count   972.000000  972.000000  972.000000  972.000000  971.000000  972.000000
mean    498.747942  190.829218    0.296296    8.254115   44.902163  111.655350
std     289.075392  163.871492    0.929362   10.479652   30.962493   66.762098
min       1.000000   11.000000    0.000000    0.000000    6.000000   10.000000
25%     248.750000   84.750000    0.000000    3.000000   24.000000   66.000000
50%     499.500000  139.000000    0.000000    5.000000   37.000000   96.000000
75%     748.250000  235.000000    0.000000   10.000000   56.000000  141.000000
max    1000.000000  979.000000   10.000000  117.000000  246.000000  606.000000

In [13]:
# Mean No. of tracks = 191, 
# SD = 164.87, 
# Max No.of tracks = 979,
# Min No. of tracks = 11    
# Median 1st quartile = 85,
# Median 2nd quartile = 139,
# Median 3rd quartile = 235

## Remove % symbol to clean up data frame for analysis later

In [14]:
# Remove % symbol to clean up data frame for analysis later

cols_to_check = ['% Songs Streamed 1Million Times', '% Songs Streamed 10Million Times', '% Songs Streamed 100Million Times', '% Songs Streamed 1Billion Times']
print(artist_df[cols_to_check])
 
artist_df[cols_to_check] = artist_df[cols_to_check].replace({'%': ''}, regex=True)
print(artist_df)

    % Songs Streamed 1Million Times % Songs Streamed 10Million Times  \
0                               98%                              97%
1                               90%                              75%
2                               99%                              95%
3                               90%                              80%
4                               97%                              70%
..                              ...                              ...
995                             79%                              13%
996                             94%                              59%
997                              8%                               2%
998                             20%                               7%
999                             16%                               6%

    % Songs Streamed 100Million Times % Songs Streamed 1Billion Times
0                                 47%                              2%
1                                 27%                              5%
2                                 63%                              2%
3                                 39%                              3%
4                                 38%                              3%
..                                ...                             ...
995                                0%                              0%
996                                2%                              0%
997                                1%                              0%
998                                3%                              0%
999                                1%                              0%

[972 rows x 4 columns]
     Position           Artist       Genre    Lead Streams Featured streams  \
0           1            Drake     Hip-Hop  45,930,207,058   17,624,649,510
1           2       Ed Sheeran         Pop  35,009,165,977    2,537,534,050
2           3        Bad Bunny  Latin Trap  33,838,992,346    4,440,723,306
3           4       The Weeknd    R&B/Soul  30,759,273,612    3,858,847,246
4           5    Ariana Grande         Pop  30,199,885,343    1,934,573,510
..        ...              ...         ...             ...              ...
995       996         Upchurch         NaN   1,233,720,207      136,998,161
996       997  Hungria Hip Hop         NaN   1,233,176,813       69,096,039
997       998          Chicago         NaN   1,232,497,152                5
998       999            Riton         NaN   1,231,385,490       21,351,886
999      1000          BIGBANG         NaN   1,231,303,296                1

     Tracks  1b  100m    10m   1m    Update % Songs Streamed 1Million Times  \
0       248   6   117  241.0  244  11.04.22                              98
1       222  10    59  166.0  200  11.04.22                              90
2       141   3    89  134.0  140  11.04.22                              99
3       178   6    69  143.0  161  11.04.22                              90
4       181   5    69  126.0  175  11.04.22                              97
..      ...  ..   ...    ...  ...       ...                             ...
995     225   0     0   29.0  177  03.03.22                              79
996      63   0     1   37.0   59  04.12.21                              94
997     725   0     4   11.0   56  22.03.22                               8
998     118   0     3    8.0   24  01.03.22                              20
999     381   0     2   23.0   60  09.04.22                              16

    % Songs Streamed 10Million Times % Songs Streamed 100Million Times  \
0                                 97                                47
1                                 75                                27
2                                 95                                63
3                                 80                                39
4                                 70                                38
..                               ...                               ...
995                               13                                 0
996                               59                                 2
997                                2                                 1
998                                7                                 3
999                                6                                 1

    % Songs Streamed 1Billion Times
0                                 2
1                                 5
2                                 2
3                                 3
4                                 3
..                              ...
995                               0
996                               0
997                               0
998                               0
999                               0

[972 rows x 15 columns]

C:\Users\VAIO\anaconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [15]:
# Check if % has been removed
artist_df.head(10)

,Position,Artist,Genre,Lead Streams,Featured streams,Tracks,1b,100m,10m,1m,Update,% Songs Streamed 1Million Times,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058","17,624,649,510",248,6,117,241.0,244,11.04.22,98,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977","2,537,534,050",222,10,59,166.0,200,11.04.22,90,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346","4,440,723,306",141,3,89,134.0,140,11.04.22,99,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612","3,858,847,246",178,6,69,143.0,161,11.04.22,90,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343","1,934,573,510",181,5,69,126.0,175,11.04.22,97,70,38,3
5,6,Justin Bieber,Pop,"29,483,883,662","10,391,249,275",222,6,55,169.0,194,11.04.22,87,76,25,3
6,7,Taylor Swift,Country,"27,839,517,025","386,434,032",319,1,76,246.0,309,11.04.22,97,77,24,0
7,8,Eminem,Hip-Hop,"27,803,863,084","3,899,986,002",279,3,60,222.0,259,11.04.22,93,80,22,1
8,9,Post Malone,Hip-Hop,"27,472,535,195","2,285,274,498",82,8,54,65.0,66,11.04.22,80,79,66,10
9,10,BTS,K-Pop,"24,789,404,457","190,636,034",253,1,88,200.0,253,11.04.22,100,79,35,0

In [16]:
artist_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 972 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Position                           972 non-null    int64
 1   Artist                             971 non-null    object
 2   Genre                              100 non-null    object
 3   Lead Streams                       972 non-null    object
 4   Featured streams                   972 non-null    object
 5   Tracks                             972 non-null    int32
 6   1b                                 972 non-null    int64
 7   100m                               972 non-null    int64
 8   10m                                971 non-null    float64
 9   1m                                 972 non-null    int64
 10  Update                             972 non-null    object
 11  % Songs Streamed 1Million Times    972 non-null    object
 12  % Songs Streamed 10Million Times   972 non-null    object
 13  % Songs Streamed 100Million Times  972 non-null    object
 14  % Songs Streamed 1Billion Times    972 non-null    object
dtypes: float64(1), int32(1), int64(4), object(9)
memory usage: 117.7+ KB

In [17]:
# Remove non essential rows - 'Featured Streams' and 'update' 
artist_df_cleaned = artist_df.drop(columns=["Featured streams","Update", "% Songs Streamed 1Million Times", "1m"])
artist_df_cleaned.head()

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3

In [18]:
# Total number of 1M songs streamed calculated for use later on
total_1M = artist_df.iloc[:10]
Total_1M = total_1M["1m"].sum()
Total_1M

2001

## Start of data analysis

# How many songs did they make on average?

In [19]:
# Total number of tracks from 1000 artists and average number of tracks per artist.

Total_Tracks = artist_df_cleaned["Tracks"].sum()
artist_count = artist_df_cleaned["Tracks"].count()
Total_number_of_Artists = str(artist_count)
#print(Total_number_of_Artists)

print(f"The Total number of Tracks in the top 1000 artist playlist are: {Total_Tracks}")
print(f"The Average number of Tracks per artist: { round(Total_Tracks / artist_count) }")

The Total number of Tracks in the top 1000 artist playlist are: 185486
The Average number of Tracks per artist: 191

In [20]:
# rename columns

artist_df_cleaned.rename(columns = {
    '1b':'1 Billion', 
    '100m':'100 Million', 
    '10m':'10 Million',
})

,Position,Artist,Genre,Lead Streams,Tracks,1 Billion,100 Million,10 Million,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Upchurch,NaN,"1,233,720,207",225,0,0,29.0,13,0,0
996,997,Hungria Hip Hop,NaN,"1,233,176,813",63,0,1,37.0,59,2,0
997,998,Chicago,NaN,"1,232,497,152",725,0,4,11.0,2,1,0
998,999,Riton,NaN,"1,231,385,490",118,0,3,8.0,7,3,0
999,1000,BIGBANG,NaN,"1,231,303,296",381,0,2,23.0,6,1,0

In [21]:
artist_df_cleaned.head()

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3

In [22]:
artist_df_cleaned.dtypes
#artist_df_cleaned["% Songs Streamed 10Million Times"]astype.

Position                               int64
Artist                                object
Genre                                 object
Lead Streams                          object
Tracks                                 int32
1b                                     int64
100m                                   int64
10m                                  float64
% Songs Streamed 10Million Times      object
% Songs Streamed 100Million Times     object
% Songs Streamed 1Billion Times       object
dtype: object

In [23]:
artist_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 972 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Position                           972 non-null    int64
 1   Artist                             971 non-null    object
 2   Genre                              100 non-null    object
 3   Lead Streams                       972 non-null    object
 4   Tracks                             972 non-null    int32
 5   1b                                 972 non-null    int64
 6   100m                               972 non-null    int64
 7   10m                                971 non-null    float64
 8   % Songs Streamed 10Million Times   972 non-null    object
 9   % Songs Streamed 100Million Times  972 non-null    object
 10  % Songs Streamed 1Billion Times    972 non-null    object
dtypes: float64(1), int32(1), int64(3), object(6)
memory usage: 87.3+ KB

In [24]:
artist_df_cleaned["% Songs Streamed 100Million Times"] = artist_df_cleaned['% Songs Streamed 100Million Times'].astype('int')
artist_df_cleaned.dtypes

Position                               int64
Artist                                object
Genre                                 object
Lead Streams                          object
Tracks                                 int32
1b                                     int64
100m                                   int64
10m                                  float64
% Songs Streamed 10Million Times      object
% Songs Streamed 100Million Times      int32
% Songs Streamed 1Billion Times       object
dtype: object

In [25]:
artist_df_cleaned["% Songs Streamed 10Million Times"] = artist_df_cleaned['% Songs Streamed 10Million Times'].astype('int')
artist_df_cleaned.dtypes

Position                               int64
Artist                                object
Genre                                 object
Lead Streams                          object
Tracks                                 int32
1b                                     int64
100m                                   int64
10m                                  float64
% Songs Streamed 10Million Times       int32
% Songs Streamed 100Million Times      int32
% Songs Streamed 1Billion Times       object
dtype: object

In [26]:
artist_df_cleaned["% Songs Streamed 1Billion Times"] = artist_df_cleaned['% Songs Streamed 1Billion Times'].astype('int')
artist_df_cleaned.dtypes

Position                               int64
Artist                                object
Genre                                 object
Lead Streams                          object
Tracks                                 int32
1b                                     int64
100m                                   int64
10m                                  float64
% Songs Streamed 10Million Times       int32
% Songs Streamed 100Million Times      int32
% Songs Streamed 1Billion Times        int32
dtype: object

# How many of them became popular?

# To find artist total tracks streamed 10 Million times greater than 80%

In [27]:
Streams_10M_df = pd.DataFrame(artist_df_cleaned.loc[artist_df_cleaned['% Songs Streamed 10Million Times']>80,:])
Streams_10M_df

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
12,13,Billie Eilish,Alternative/Indie pop,"21,436,789,653",62,4,41,57.0,92,66,6
13,14,Juice WRLD,Hip-Hop,"21,084,148,801",117,2,57,112.0,96,49,2
30,31,Kendrick Lamar,Hip-Hop,"15,193,196,132",103,1,32,91.0,88,31,1
32,33,One Direction,Pop,"14,224,545,475",124,0,42,100.0,81,34,0
42,43,Adele,Pop Soul,"12,995,508,731",70,3,24,59.0,84,34,4
46,47,Twenty One Pilots,Alternative Rock,"12,230,092,784",90,3,34,74.0,82,38,3
48,49,Lil Uzi Vert,Hip-Hop,"11,981,431,319",129,1,30,117.0,91,23,1
50,51,Kygo,Electronic dance,"11,824,039,530",102,1,28,85.0,83,27,1
66,67,Harry Styles,Pop,"9,137,076,671",27,3,24,25.0,93,89,11
85,86,Pop Smoke,Hip-Hop,"8,114,250,149",98,0,18,79.0,81,18,0
91,92,Lil Peep,Emo Rap,"7,807,725,799",101,0,21,87.0,86,21,0
94,95,Lil Nas X,Pop,"7,710,176,745",33,3,11,30.0,91,33,9
113,114,NF,NaN,"7,063,003,125",81,1,16,81.0,100,20,1
115,116,Frank Ocean,NaN,"7,029,867,946",45,0,21,45.0,100,47,0
149,150,MarÃ­lia MendonÃ§a,NaN,"6,021,692,420",117,0,22,105.0,90,19,0
163,164,Polo G,NaN,"5,638,343,072",75,0,13,67.0,89,17,0
164,165,The Kid LAROI,NaN,"5,583,045,467",47,1,15,42.0,89,32,2
167,168,Camilo,NaN,"5,558,966,861",39,0,20,35.0,90,51,0
183,184,Luke Combs,NaN,"5,183,194,117",56,0,15,55.0,98,27,0
196,197,System Of A Down,NaN,"4,914,276,934",84,0,9,68.0,81,11,0
198,199,Joji,NaN,"4,891,769,766",50,0,14,41.0,82,28,0
210,211,Bazzi,NaN,"4,734,399,866",37,0,12,32.0,86,32,0
214,215,Paulo Londra,NaN,"4,648,248,854",30,0,13,29.0,97,43,0
216,217,Christian Nodal,NaN,"4,622,776,903",62,0,13,50.0,81,21,0
251,252,Morgan Wallen,NaN,"4,233,018,031",58,0,11,58.0,100,19,0
258,259,Morat,NaN,"4,185,875,702",70,0,11,59.0,84,16,0
286,287,Ryan Lewis,NaN,"3,896,682,000",33,1,6,28.0,85,18,3
361,362,Daniel Caesar,NaN,"3,114,399,368",38,0,7,35.0,92,18,0
375,376,Alec Benjamin,NaN,"3,016,113,741",34,1,7,31.0,91,21,3
380,381,MÃ¥neskin,NaN,"2,990,300,974",31,0,6,28.0,90,19,0
398,399,Conan Gray,NaN,"2,879,943,163",26,0,6,26.0,100,23,0
419,420,Bon Iver,NaN,"2,770,728,013",45,0,6,37.0,82,13,0
438,439,Bradley Cooper,NaN,"2,666,104,022",12,1,4,10.0,83,33,8
468,469,Normani,NaN,"2,503,197,119",16,0,4,13.0,81,25,0
473,474,PNL,NaN,"2,491,153,666",72,0,2,66.0,92,3,0
552,553,Clairo,NaN,"2,141,415,867",25,0,7,25.0,100,28,0
597,598,Ella Mai,NaN,"1,987,800,591",39,0,6,34.0,87,15,0
728,729,Cigarettes After Sex,NaN,"1,677,280,509",30,0,4,28.0,93,13,0
782,783,Beret,NaN,"1,586,857,502",48,0,3,40.0,83,6,0
847,848,MatuÃª,NaN,"1,446,021,815",33,0,3,27.0,82,9,0
865,866,Giveon,NaN,"1,423,652,277",18,0,3,18.0,100,17,0
953,954,Silk Sonic,NaN,"1,294,272,147",11,0,3,11.0,100,27,0

In [50]:
data_10M = Streams_10M_df[["Artist","% Songs Streamed 10Million Times"]]
Sum_Streams_10M_df = Streams_10M_df["10m"].sum()
print(f"The Number of Artists with the majority of their Tracks (80%) streaming 10 Million Times is: {len(data_10M)}")
print("--------------------------------------------------------------")
print(f"The Sum of All the tracks Artist streams over 10 Million: {round(Sum_Streams_10M_df)}")
print("--------------------------------------------------------------")
print(f"The Average Number of Tracks streaming 10 Million times is : {round(Sum_Streams_10M_df/44)}%")

The Number of Artists with the majority of their Tracks (80%) streaming 10 Million Times is: 44
--------------------------------------------------------------
The Sum of All the tracks Artist streams over 10 Million: 2515
--------------------------------------------------------------
The Average Number of Tracks streaming 10 Million times is : 57%

In [29]:
data_10M = Streams_10M_df[["Artist","% Songs Streamed 10Million Times"]]

print(f"The Number of Artists with the majority of their Tracks (80%) streaming 100 Million Times is : {len(data_10M)}")

The Number of Artists with the majority of their Tracks (80%) streaming 100 Million Times is : 44

In [30]:
Artist_names_10M = data_10M["Artist"].unique

# Bar chart for percentages of popular songs

In [31]:
Artist_names_10M = data_10M["Artist"].unique
x_axis = Streams_10M_df["Artist"]
streams = Streams_10M_df["% Songs Streamed 10Million Times"]
fig1, ax1 = plt.subplots(figsize=(10,14))

plt.bar(x_axis,streams, color='red', alpha=0.8, align='center')

plt.xticks( rotation='vertical')

plt.title("Artist passing 80% of songs in 10Million streams")
plt.xlabel("Artist")

plt.xlim(-0.75, len(x_axis)-0.25)
plt.ylim(75, 101)
plt.ylabel("Streams %")
plt.savefig("Project1_BarChart1.png")

In [32]:
Streams_100M_df = pd.DataFrame(artist_df_cleaned.loc[artist_df_cleaned['% Songs Streamed 100Million Times']>35,:])
Streams_100M_df

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3
8,9,Post Malone,Hip-Hop,"27,472,535,195",82,8,54,65.0,79,66,10
12,13,Billie Eilish,Alternative/Indie pop,"21,436,789,653",62,4,41,57.0,92,66,6
13,14,Juice WRLD,Hip-Hop,"21,084,148,801",117,2,57,112.0,96,49,2
20,21,Travis Scott,Hip-Hop,"19,184,512,661",112,3,43,90.0,80,38,3
25,26,Bruno Mars,Electronic dance,"16,495,189,532",79,5,31,61.0,77,39,6
46,47,Twenty One Pilots,Alternative Rock,"12,230,092,784",90,3,34,74.0,82,38,3
55,56,Camila Cabello,Pop Latin,"10,718,386,609",60,2,23,43.0,72,38,3
66,67,Harry Styles,Pop,"9,137,076,671",27,3,24,25.0,93,89,11
115,116,Frank Ocean,NaN,"7,029,867,946",45,0,21,45.0,100,47,0
133,134,SZA,NaN,"6,412,432,497",41,1,18,33.0,80,44,2
167,168,Camilo,NaN,"5,558,966,861",39,0,20,35.0,90,51,0
214,215,Paulo Londra,NaN,"4,648,248,854",30,0,13,29.0,97,43,0

In [52]:
data_100M = Streams_100M_df[["Artist","% Songs Streamed 100Million Times"]]
Sum_Streams_100M_df = Streams_100M_df["100m"].sum()
print(f"From the top 100 Artist the Number of Artists streaming over 34% of their track 100 Million times is : {len(data_100M)}")
print("--------------------------------------------------------------")
print(f"The Sum of All Artist streams over 100 Million: {Sum_Streams_100M_df}")
print("--------------------------------------------------------------")
print(f"The Average Number of Tracks streaming 100 Million times is : {round(Sum_Streams_100M_df/16)}")

From the top 100 Artist the Number of Artists streaming over 34% of their track 100 Million times is : 16
--------------------------------------------------------------
The Sum of All Artist streams over 100 Million: 723
--------------------------------------------------------------
The Average Number of Tracks streaming 100 Million times is : 45

In [ ]:
data_100M = Streams_100M_df[["Artist","% Songs Streamed 100Million Times"]]

print(f"The Number of Artists at least 35% of thier tracks 100 Million Times is : {len(data_100M)}")

In [ ]:
data_100M["Artist"].unique

In [ ]:
#created list of Artist for x axis using unique function

x_axis = Streams_100M_df["Artist"]
streams = Streams_100M_df["% Songs Streamed 100Million Times"]
fig1, ax1 = plt.subplots(figsize=(7, 12))


plt.bar(x_axis,streams, facecolor="m", alpha=0.8, align='center')
tick_locations = [value for value in x_axis]
plt.xticks(tick_locations, ['Drake','Bad Bunny', 'The Weeknd', 'Ariana Grande', 'Post Malone', 'Billie Eilish', 'Juice WRLD', 'Travis Scott', 'Bruno Mars', 'Twenty One Pilots', 'Camila Cabello', 'Harry Styles', 'Frank Ocean', 'SZA', 'Camilo', 'Paulo Londra'],  rotation='vertical')

plt.xlim(-0.75,len(x_axis)-0.25)
plt.ylim(20, 94)
plt.title("Artist passing 35% of songs in 100Million streams")
plt.xlabel("Artist")
plt.ylabel("Streams %")
plt.savefig("Project1_BarChart2.png")

In [55]:
Streams_1B = pd.DataFrame(artist_df_cleaned.loc[artist_df_cleaned['% Songs Streamed 1Billion Times']>1,:])
Streams_1B

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3
...,...,...,...,...,...,...,...,...,...,...,...
712,713,Dynoro,NaN,"1,704,509,405",17,1,3,9.0,53,18,6
721,722,Trevor Daniel,NaN,"1,684,760,342",48,1,2,12.0,25,4,2
748,749,beabadoobee,NaN,"1,641,802,433",59,1,1,9.0,15,2,2
762,763,Powfu,NaN,"1,617,907,608",66,1,1,12.0,18,2,2
926,927,Gotye,NaN,"1,333,444,133",46,1,1,9.0,20,2,2

In [56]:
Streams_1B_df = pd.DataFrame(artist_df_cleaned.loc[artist_df_cleaned['% Songs Streamed 1Billion Times']>2,:])
Streams_1B_df

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3
5,6,Justin Bieber,Pop,"29,483,883,662",222,6,55,169.0,76,25,3
8,9,Post Malone,Hip-Hop,"27,472,535,195",82,8,54,65.0,79,66,10
12,13,Billie Eilish,Alternative/Indie pop,"21,436,789,653",62,4,41,57.0,92,66,6
15,16,XXXTENTACION,Hip-Hop,"19,953,049,106",131,7,42,104.0,79,32,5
17,18,Khalid,R&B/Soul,"19,690,052,960",111,7,39,86.0,77,35,6
18,19,Dua Lipa,Pop,"19,665,995,562",193,6,33,80.0,41,17,3
19,20,Imagine Dragons,Alternative/Indie pop,"19,596,416,938",146,4,39,108.0,74,27,3
20,21,Travis Scott,Hip-Hop,"19,184,512,661",112,3,43,90.0,80,38,3
23,24,Shawn Mendes,Pop,"17,706,595,827",126,4,33,94.0,75,26,3
25,26,Bruno Mars,Electronic dance,"16,495,189,532",79,5,31,61.0,77,39,6
28,29,Sam Smith,Pop,"15,908,097,736",139,4,30,81.0,58,22,3
42,43,Adele,Pop Soul,"12,995,508,731",70,3,24,59.0,84,34,4
46,47,Twenty One Pilots,Alternative Rock,"12,230,092,784",90,3,34,74.0,82,38,3
47,48,Marshmello,Electronic dance,"12,078,260,875",143,4,17,83.0,58,12,3
55,56,Camila Cabello,Pop Latin,"10,718,386,609",60,2,23,43.0,72,38,3
66,67,Harry Styles,Pop,"9,137,076,671",27,3,24,25.0,93,89,11
73,74,Charlie Puth,Pop,"8,485,914,369",102,3,12,56.0,55,12,3
74,75,Cardi B,Hip-Hop,"8,477,939,050",67,2,18,51.0,76,27,3
94,95,Lil Nas X,Pop,"7,710,176,745",33,3,11,30.0,91,33,9
101,102,ZAYN,NaN,"7,511,901,161",85,3,15,67.0,79,18,4
107,108,Olivia Rodrigo,NaN,"7,340,845,148",37,2,12,23.0,62,32,5
131,132,Lewis Capaldi,NaN,"6,507,617,673",48,2,9,28.0,58,19,4
218,219,Hailee Steinfeld,NaN,"4,589,558,265",29,1,10,18.0,62,34,3
286,287,Ryan Lewis,NaN,"3,896,682,000",33,1,6,28.0,85,18,3
308,309,Tones And I,NaN,"3,697,594,279",30,1,5,15.0,50,17,3
338,339,benny blanco,NaN,"3,337,797,101",20,1,6,12.0,60,30,5
375,376,Alec Benjamin,NaN,"3,016,113,741",34,1,7,31.0,91,21,3
394,395,Dean Lewis,NaN,"2,903,655,994",40,1,6,25.0,63,15,3
438,439,Bradley Cooper,NaN,"2,666,104,022",12,1,4,10.0,83,33,8
514,515,DNCE,NaN,"2,280,705,753",32,1,4,18.0,56,13,3
619,620,Arizona Zervas,NaN,"1,932,876,803",32,1,2,15.0,47,6,3
712,713,Dynoro,NaN,"1,704,509,405",17,1,3,9.0,53,18,6

In [57]:
Streams_1B_df["1b"].sum()

119

In [59]:
data_1B = Streams_1B_df[["Artist","% Songs Streamed 1Billion Times"]]
Sum_Streams_1B_df = Streams_1B_df["1b"].sum()
print(f"The Number of Artists streaming over 2 Billion times is : {len(data_1B)}")
print("--------------------------------------------------------------")
#print (f"The total Artists streaming over 2 Billion times is : {(sum_data_1B.max()}")
print("--------------------------------------------------------------")
print(f"The Sum of All Artist streaming over 2 Billion:{Sum_Streams_1B_df}")
print("--------------------------------------------------------------")
print(f"The Average Number of Artists streaming over 2 Billion times is : {round(Sum_Streams_1B_df/35)}%")

The Number of Artists streaming over 2 Billion times is : 35
--------------------------------------------------------------
--------------------------------------------------------------
The Sum of All Artist streaming over 2 Billion:119
--------------------------------------------------------------
The Average Number of Artists streaming over 2 Billion times is : 3%

In [ ]:
data_1B["Artist"].unique

In [ ]:
x_axis = Streams_1B_df["Artist"]
streams = Streams_1B_df["% Songs Streamed 1Billion Times"]
fig1, ax1 = plt.subplots(figsize=(12,14))


plt.bar(x_axis,streams, facecolor="b", alpha=0.8, align='center')
tick_locations = [value for value in x_axis]
plt.xticks(tick_locations, ['Ed Sheeran', 'The Weeknd', 'Ariana Grande', 'Justin Bieber', 'Post Malone', 'Billie Eilish', 'XXXTENTACION', 'Khalid',
'Dua Lipa', 'Imagine Dragons', 'Travis Scott', 'Shawn Mendes', 'Bruno Mars', 'Sam Smith', 'Adele', 'Twenty One Pilots', 'Marshmello', 
'Camila Cabello', 'Harry Styles', 'Charlie Puth', 'Cardi B', 'Lil Nas X', 'ZAYN', 'Olivia Rodrigo', 'Lewis Capaldi', 'Hailee Steinfeld', 
'Ryan Lewis', 'Tones And I', 'Benny blanco', 'Alec Benjamin', 'Dean Lewis', 'Bradley Cooper', 'DNCE', 'Arizona Zervas', 'Dynoro'],  rotation='vertical')


plt.xlim(-0.75, len(x_axis)-0.25)
plt.ylim(0, 12)
plt.title("Any Artist Streaming Over 1 Billion Times")
plt.xlabel("Artist")
plt.ylabel("Streams %")

plt.show()
plt.savefig("Project1_BarChart3.png")

# Is there a difference with the top 10?

# Top 1000 artist analysis

In [36]:
artist_df_cleaned.head()

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3

In [37]:
# Artist with the greatset number of tracks released
Total_Tracks = artist_df_cleaned["Tracks"].sum()
Max_Tracks = artist_df_cleaned["Tracks"].max()

# Artist with the least number of tracks released
Min_Tracks = artist_df_cleaned["Tracks"].min()
print(f"The total number of tracks in the top 1000 artist are :{Total_Tracks}")
print(f"In the artist charts the maximum number of tracks released by an artist was :{Max_Tracks} and the least number of tracks released was {Min_Tracks}")

The total number of tracks in the top 1000 artist are :185486
In the artist charts the maximum number of tracks released by an artist was :979 and the least number of tracks released was 11

In [38]:
Min_10m = artist_df_cleaned["10m"].min()
Max_10m = artist_df_cleaned["10m"].max()

Min_100m = artist_df_cleaned["100m"].min()
Max_100m = artist_df_cleaned["100m"].max()

Min_1b = artist_df_cleaned["1b"].min()
Max_1b = artist_df_cleaned["1b"].max()

In [39]:
print(f"In the Top 1000 artist, the minimum streams reaching 10 Million are {Min_10m} and maximum are {Max_10m}")
print("----------------------------------------------------------------------------")
print(f"In the Top 1000 artist, the minimum streams reaching 100 Million are {Min_100m} and maximum are {Max_100m}")
print("----------------------------------------------------------------------------")
print(f"In the Top 1000 artist, the minimum streams reaching 1 Billion are {Min_1b} and maximum are {Max_1b}")

In the Top 1000 artist, the minimum streams reaching 10 Million are 6.0 and maximum are 246.0
----------------------------------------------------------------------------
In the Top 1000 artist, the minimum streams reaching 100 Million are 0 and maximum are 117
----------------------------------------------------------------------------
In the Top 1000 artist, the minimum streams reaching 1 Billion are 0 and maximum are 10

# Top 100 artist analysis

In [ ]:
Top_100_artist_df = artist_df_cleaned.iloc[:100]
Top_100_artist_df

In [ ]:
Total_Tracks_top_100 = Top_100_artist["Tracks"].sum()
Total_10m_top_100 = Top_100_artist["10m"].sum()
Total_100m_top_100 = np.mean(Top_100_artist["10m"]).sum()
Total_1b_top_100 = Top_100_artist["1b"].sum()

print(f"The Total tracks in top 100 artist is: {Total_Tracks_top_100}")
print("--------------------------------------------------------------")
print(f"The Total tracks streamed 10 Million times in top 100 artist is: {round(Total_10m_top_100)}")
print("--------------------------------------------------------------")
print(f"The Total tracks streamed 100 Million times in top 100 artist is: {Total_100m_top_100}")
print("--------------------------------------------------------------")
print(f"The Total tracks streamed 1 Billion times in top 100 artist is: {Total_1b_top_100}")

In [ ]:
Min_Tracks = Top_100_artist["Tracks"].min()
Max_Tracks = Top_100_artist["Tracks"].max()

print(f"The minimum number of tracks relseased by an artist in the top 100 artist is :{Min_Tracks}")
print(f"The maximum number of tracks relseased by an artist in the top 100 artist is :{Max_Tracks}")

In [ ]:
avg_top_100_10M = np.mean(Top_100_artist["10m"])
avg_top_100_100M = np.mean(Top_100_artist["100m"])
avg_top_100_1B = np.mean(Top_100_artist["1b"])

print(f"The average number of 10 Million streams in the top 100 artist are :{round(avg_top_100_10M)} ")
print(f"The average number of 100 Million streams in the top 100 artist are :{round(avg_top_100_100M)} ")
print(f"The average number of 1 Billion streams in the top 100 artist are :{round(avg_top_100_1B)} ")

# Top 10 artist analysis

In [40]:
top_10_df = artist_df_cleaned.iloc[:10]
top_10_df

,Position,Artist,Genre,Lead Streams,Tracks,1b,100m,10m,% Songs Streamed 10Million Times,% Songs Streamed 100Million Times,% Songs Streamed 1Billion Times
0,1,Drake,Hip-Hop,"45,930,207,058",248,6,117,241.0,97,47,2
1,2,Ed Sheeran,Pop,"35,009,165,977",222,10,59,166.0,75,27,5
2,3,Bad Bunny,Latin Trap,"33,838,992,346",141,3,89,134.0,95,63,2
3,4,The Weeknd,R&B/Soul,"30,759,273,612",178,6,69,143.0,80,39,3
4,5,Ariana Grande,Pop,"30,199,885,343",181,5,69,126.0,70,38,3
5,6,Justin Bieber,Pop,"29,483,883,662",222,6,55,169.0,76,25,3
6,7,Taylor Swift,Country,"27,839,517,025",319,1,76,246.0,77,24,0
7,8,Eminem,Hip-Hop,"27,803,863,084",279,3,60,222.0,80,22,1
8,9,Post Malone,Hip-Hop,"27,472,535,195",82,8,54,65.0,79,66,10
9,10,BTS,K-Pop,"24,789,404,457",253,1,88,200.0,79,35,0

In [ ]:
top_10_df.describe()

In [49]:
# Max and Min Artist with 10m 100m and 1b

print(f"The Artist with the most 10 Million streams in the top 10 is: Taylor Swift with 246 tracks.")
print("-----------------------------------------------------------------------------------")
print(f"The Artist with the least 10 Million streams in the top 10 is: Post Malone with 65 tracks.")
print("-----------------------------------------------------------------------------------")
print(f"The Artist with the most 100 Million streams in the top 10 is: Drake with 117 tracks.")
print("-----------------------------------------------------------------------------------")
print(f"The Artist with the least 100 Million streams in the top 10 is: Post Malone with 54 tracks.")
print("-----------------------------------------------------------------------------------")
print(f"The Artist with the most 1 Billion streams in the top 10 is: Ed Sheeran with 10 tracks.")
print("-----------------------------------------------------------------------------------")
print(f"The Artist with the least 1 Billion streams in the top 10 is: Taylor Swift & BTS with 1 track.")
print("-----------------------------------------------------------------------------------")


print(f"The Artist with the highest track releases is Taylor Swift with 319.")
print("-----------------------------------------------------------------------------------")
print(f"The Artist with the fewest track releases is Post Malone with 82.")
print("-----------------------------------------------------------------------------------")

print("-----------------------------------------------------------------------------------")

print("-----------------------------------------------------------------------------------")

The Artist with the most 10 Million streams in the top 10 is: Taylor Swift with 246 tracks.
-----------------------------------------------------------------------------------
The Artist with the least 10 Million streams in the top 10 is: Post Malone with 65 tracks.
-----------------------------------------------------------------------------------
The Artist with the most 100 Million streams in the top 10 is: Drake with 117 tracks.
-----------------------------------------------------------------------------------
The Artist with the least 100 Million streams in the top 10 is: Post Malone with 54 tracks.
-----------------------------------------------------------------------------------
The Artist with the most 1 Billion streams in the top 10 is: Ed Sheeran with 10 tracks.
-----------------------------------------------------------------------------------
The Artist with the least 1 Billion streams in the top 10 is: Taylor Swift & BTS with 1 track.
-----------------------------------------------------------------------------------
The Artist with the highest track releases is Taylor Swift with 319.
-----------------------------------------------------------------------------------
The Artist with the fewest track releases is Post Malone with 82.
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------
-----------------------------------------------------------------------------------

In [42]:
Top_Ten_Total_Tracks = top_10_df["Tracks"].sum()

# calculate total number of tracks streaming 10 Million
top_10m_total_tracks = top_10_df["10m"].sum()

# calculate total number of tracks streaming 100 Million
top_100m_total_tracks = top_10_df["100m"].sum()

# calculate total number of tracks streaming 1 Billion
top_1b_total_tracks = top_10_df["1b"].sum()

# calculate mean number of tracks streaming 10 Million
avg_top_10m_total_tracks = top_10m_total_tracks/10

# calculate mean number of tracks streaming 100 Million
avg_top_100m_total_tracks = top_100m_total_tracks/10

# calculate mean number of tracks streaming 1 Billion
avg_top_1b_total_tracks = top_1b_total_tracks/10

# Calculate median of 10m
#np.median("Tracks")

print(f" The total number of tracks in the top ten artist are: {Top_Ten_Total_Tracks + Total_1M}")
print("-----------------------------------------------------------------------------")
print(f" The Total number of tracks from the top ten artist reaching 10 Million are: {top_10m_total_tracks}")
print("-----------------------------------------------------------------------------")
print(f" The Total number of tracks from the top ten artist reaching 100 Million are: {top_100m_total_tracks}")
print("-----------------------------------------------------------------------------")
print(f" The Total number of tracks from the top ten artist reaching 1 Billion are: {top_1b_total_tracks}")

 The total number of tracks in the top ten artist are: 4126
-----------------------------------------------------------------------------
 The Total number of tracks from the top ten artist reaching 10 Million are: 1712.0
-----------------------------------------------------------------------------
 The Total number of tracks from the top ten artist reaching 100 Million are: 736
-----------------------------------------------------------------------------
 The Total number of tracks from the top ten artist reaching 1 Billion are: 49

In [44]:
print(f" The Average number of tracks from the top ten artist reaching 10 Million are: {round(avg_top_10m_total_tracks)}")
print(f" The Average number of tracks from the top ten artist reaching 100 Million are: {round(avg_top_100m_total_tracks)}")
print(f" The Average number of tracks from the top ten artist reaching 1 Billion are: {round(avg_top_1b_total_tracks)}")

 The Average number of tracks from the top ten artist reaching 10 Million are: 171
 The Average number of tracks from the top ten artist reaching 100 Million are: 74
 The Average number of tracks from the top ten artist reaching 1 Billion are: 5

In [43]:
# Calculate median of 10m
median_10m = top_10_df["10m"]
np.median(median_10m)

# Calculate median of 10m
median_100m = top_10_df["100m"]
np.median(median_100m)

# Calculate median of 10m
median_1b = top_10_df["1b"]
np.median(median_1b)


print(f"The median for tracks in 10 Million streams is: {np.median(median_10m)}")
print(f"The median for tracks in 100 Million streams is: {np.median(median_100m)}")
print(f"The median for tracks in 1 Billion streams is: {np.median(median_1b)}")

The median for tracks in 10 Million streams is: 167.5
The median for tracks in 100 Million streams is: 69.0
The median for tracks in 1 Billion streams is: 5.5

# What is the most popular genre?

In [ ]:
# Create index with genre type for statistical analysis 
Genres = artist_df_cleaned["Genre"].unique()

In [ ]:
len(Genres)

In [ ]:
Genres

In [ ]:
# Create index with genres
Top_100_artist = Top_100_artist.set_index("Genre")
Top_100_artist

In [ ]:
n = Top_100_artist_df.groupby("Genre")

# Pie chart for distribution of genres

In [ ]:
count_genre_types = n["Genre"].count()
count_genre_types

In [ ]:
#Merged (Raggaeton & Reggaeton) also  (Progressive House & progressive house electro house)

label_1 = ["Alternative Hip-Hop", "Alternative Rock", "Alternative/Indie pop", "Country", 
           "Country Pop", "Dance-pop", "Electro Pop", "Electronic dance", 
           "Emo Rap", "Funk Rock ", "Heavy Metal", "Hip-Hop", 
           "Hip-Hop B&B", "Indie Pop", "Indie Rock", "K-Pop", 
           "Latin Hip-Hop", "Latin Pop", "Latin R&B", "Latin Raggaeton", 
           "Latin Trap", "Pop", "Pop Soul", "Pop Latin", 
           "Pop Punk", "Pop Rock", "Progressive House", "R&B/Soul", 
           "Raggaeton", "Rock"]
sizes_1 = [1, 2, 4, 1, 1, 2, 1, 9, 1, 1, 1, 22, 1, 1, 2, 1, 1, 1, 2, 1, 1, 21, 1, 1, 1, 2, 2, 4, 8, 3]
colors = ['r','g','b','c','m','y','r','g','b','c','m','silver','r','g','b','c','m','silver','r','g','b','c','m','silver',
         'r','g','b','c','m','y']
explode = (0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0.1, 0)
fig1, ax1 = plt.subplots(figsize=(10, 10))           
plt.pie(sizes_1, labels=label_1, explode= explode, colors=colors, shadow=True, startangle=55)
plt.savefig("Project_1_Pie_Chart.png")

In [ ]:
# using the top 7 categories to create pie chart (*****NOTE due to typo merging 'Raggaeton' and 'Reggaeton')

labels = ["Alternative/Indie pop", "Electronic dance", "Hip-Hop", "Pop", "R&B/Soul", "Raggaeton", "Rock" ]

sizes = [4, 9, 22, 21, 4, 8, 3]

colors = ['r','silver','purple','lightcoral','lightseagreen','darkorange', 'b']

explode = (0, 0, 0.08, 0, 0, 0.07, 0)
fig1, ax1 = plt.subplots(figsize=(10, 10)) 
plt.pie(sizes, explode=explode, labels=labels, colors=colors,
        autopct="%1.0f%%", shadow=True, startangle=55)
plt.savefig("Project_1_Pie_chart2.png")

In [ ]:
plt.axis("equal")